// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts
export const Formats: FormatList = [
	{
        name: "[Gen 8] Novrai Region",
        desc: `<b>Novrai Region</b>: The Showdown mod that finally lets Novrai Pokémon be used.`,
        threads: [
            `&bullet; <a href="https://docs.google.com/spreadsheets/d/1AgIUTqnZhqDw63uUUPLERUevM2pVJZRbaeswVPi3XAg/edit?usp=sharing">Spreadsheet</a>`,
        ],
        mod: 'novrairegion',
        ruleset: ['Standard NatDex', 'Dynamax Clause', 'Sleep Clause Mod', 'Species Clause', 'Moody Clause', 'Evasion Moves Clause', 'Swagger Clause', 'Baton Pass Clause', 'OHKO Clause'],
        banlist: ['All Pokemon', 'Normalium Z', 'Fairium Z', 'Fightinium Z', 'Firium Z', 'Flyinium Z', 'Darkinium Z', 'Dragonium Z', 'Buginium Z', 'Waterium Z', 'Electrium Z', 'Ghostium Z', 'Grassium Z', 'Groundium Z', 'Icium Z', 'Poisonium Z', 'Psychium Z', 'Rockium Z', 'Steelium Z',],
        unbanlist: [
			'Snipsnap', 'Crable', 'Lobstrike', 'Impyre', 'Incubat', 'Nocturnace', 'Scuddle', 'Bubbeetle', 'Cascarapace', 'Fervole', 'Volentine', 'Bidoof', 'Bibarel', 'Sidepeck',
			'Justork', 'Superheron', 'Hoothoot', 'Noctowl', 'Dusby', 'Dusturby', 'Gourmaggot', 'Pheromage', 'Winture', 'Expolar', 'Snorunt', 'Glalie', 'Froslass', 'Snom',
			'Frosmoth', 'Zubat', 'Golbat', 'Crobat', 'Bijarre', 'Phantique', 'Roggenrola', 'Boldore', 'Gigalith', 'Glaburrow', 'Glaborehol', 'Neurymph', 'Cognisalis', 'Memosquito',
			'Wibow', 'Tarantailor', 'Peculine', 'Quezabeast', 'Budew', 'Roselia', 'Roserade', 'Combee', 'Vespiquen', 'Cherubi-Novrai', 'Cherrim-Novrai', 'Nectair', 'Soarup', 'Lillipup',
			'Herdier-Novrai', 'Stoutland-Novrai', 'Vileech', 'Encreech', 'Yolkoo', 'Cantankoo', 'Bonsly-Novrai', 'Sudowoodo-Novrai', 'Happiny', 'Chansey', 'Blissey', 'Whispore', 'Mysoleum',
			'Sewaddle', 'Swadloon', 'Leavanny', 'Gorgarden', 'Kudzusa', 'Cutiefly', 'Ribombee', 'Pichu', 'Pikachu', 'Raichu', 'Azurill', 'Marill', 'Azumarill', 'Bonsquire', 'Campsire',
			'Tandemaus', 'Maushold', 'Smeargle', 'Sockback', 'Blockstack', 'Abra', 'Kadabra', 'Alakazam', 'Munna', 'Musharna', 'Platypull', 'Magnetreme', 'Tympole', 'Palpitoad', 'Seismitoad',
			'Narysite', 'Condyceps', 'Onix', 'Steelix', 'Magikarp', 'Gyarados', 'Dekoi', 'Imitacean', 'Snoozea', 'Sosola', 'Atlaxocean', 'Eyeti', 'Cerebarrel', 'Binacle', 'Barbaracle',
			'Wattrel', 'Kilowattrel', 'Shellos', 'Gastrodon', 'Shellder', 'Cloyster', 'Infestinal', 'Horrendible', 'Chinchou', 'Lanturn', 'Slugic', 'Noudini', 'Candleru', 'Smeltdown',
			'Exfinguish', 'Horsea', 'Seadra', 'Kingdra', 'Marimigo', 'Knapback', 'Bulkpack', 'Heftersack', 'Houndour', 'Houndoom', 'Slowpoke-Novrai', 'Slowbro-Novrai', 'Slowking-Novrai',
			'Exeggcute', 'Exeggutor', 'Pineco', 'Forretress', 'Puppanzee', 'Gorilloquy', 'Drumble', 'Draggop', 'Draborate', 'Atmosoft', 'Nimbluff', 'Stormendous', 'Chillow', 'Mattreeze',
			'Swirlix', 'Slurpuff', 'Wooloo-Novrai', 'Dubwool-Novrai', 'Kitterwaul', 'Impawzible', 'Gliderweb', 'Sunglew', 'Drozerain', 'Mushmettle', 'Smashkebab', 'Puppond', 'Pembrook',
			'Ratten', 'Possessum', 'Splattod', 'Vandibal', 'Jalopig', 'Hotrog', 'Varoom', 'Revavroom', 'Grenaize', 'Blastalk', 'Coboom', 'Deerling', 'Sawsbuck', 'Dimwatt', 'Bulbright',
			'Brillumint', 'Alkaalite', 'Oblittery', 'Durassault', 'Kookout', 'Ovection', 'Tunnowl', 'Prospecktor', 'Raptorado', 'Aron', 'Lairon', 'Aggron', 'Playmight', 'Khanstruct',
			'Graemblin', 'Gangraeae', 'Seekore', 'Ransaxe', 'Rasgold', 'Glimmet', 'Glimmora', 'Noibat', 'Noivern', 'Caughtton', 'Amalgarment', 'Peepsqueak', 'Malloon', 'Ralts', 'Kirlia',
			'Gardevoir', 'Gallade', 'Itachill', 'Itaffura', 'Slippetal', 'Pistiletto', 'Athlace', 'Athcleat', 'Togepi', 'Togetic', 'Togekiss', 'Acipeasi', 'Zestatic', 'Venonat', 'Venomoth',
			'Fawntom', 'Morboose', 'Yanma', 'Yanmega', 'Verminion', 'Abdominion', 'Miscuit', 'Maliscuit', 'Bananza', 'Morostache', 'Impostache', 'Morosquatch', 'Tangela', 'Tangrowth',
			'Herbald', 'Toupe\u0301ary', 'Heracross', 'Fistiscuff', 'Elegent', 'Sacretary', 'Gastly', 'Haunter', 'Gengar', 'Glumbrella', 'Pourasoul', 'Greavard', 'Houndstone', 'Spookebal',
			'Spiritomb', 'Clobbopus-Novrai', 'Grapploct-Novrai', 'Sandygast', 'Palossand', 'Wrassure', 'Wrassuage', 'Wrassassin', 'Staryu', 'Starmie', 'Baytate', 'Perilscope', 'Skrelp-Novrai',
			'Dragalge-Novrai', 'Clauncher', 'Clawitzer', 'Nemosis', 'Anembidex', 'Jigglwiggl', 'Bogglwoggl', 'Pyukumuku-Novrai', 'Spectracle', 'Scargot', 'Magnemite', 'Magneton', 'Magnezone',
			'X-Trac', 'X-Parament', 'Joltik', 'Galvantula', 'Widgix', 'Damastrophe', 'Porygon', 'Porygon2', 'Porygon-Z', 'Ditto', 'Rotom', 'Rotom-Heat', 'Rotom-Wash', 'Rotom-Frost',
			'Rotom-Fan', 'Rotom-Mow', 'Encryptid', 'Rhyhorn', 'Rhydon', 'Rhyperior', 'Scraggy', 'Scrafty', 'Upchick', 'Carriannon', 'Rellor', 'Rabsca', 'Hatenna-Novrai', 'Hattrem-Novrai',
			'Hatterene-Novrai', 'Impidimp-Novrai', 'Morgrem-Novrai', 'Grimmsnarl-Novrai', 'Darumaka', 'Darmanitan', 'Darmanitan-Zen', 'Grimer-Novrai', 'Muk-Novrai', 'Bramblin', 'Brambleghast',
			'Helioptile', 'Heliolisk', 'Kuloff', 'Kuldown', 'Ferroseed', 'Ferrothorn', 'Cacnea', 'Cacturne', 'Ampaconda', 'Spiraclean', 'Orthworm', 'Ambug', 'Carambug', 'Spinostern',
			'Overroard', 'Cranidos-Novrai', 'Rampardos-Novrai', 'Omanyte-Novrai', 'Omastar-Novrai', 'Cambryo', 'Palaeodox', 'Granvas', 'Mezosaic', 'Aerodactyl', 'Fosteraptor', 'Sizzlipede',
			'Centiskorch', 'Itcheep', 'Poxadoodle', 'Minsect', 'Crawlycane', 'Vanillite-Novrai', 'Vanillish-Novrai', 'Vanilluxe-Novrai', 'Shivrr', 'Icecreep', 'Quaintbrush', 'Blendulum',
			'Thinkblot', 'Rorschade', 'Scholarva', 'Intellibee', 'Unown', 'Unown-Omega', 'Kreakup', 'Krackpot', 'Haloe', 'Aloverity', 'Diretom', 'Eruptide', 'Plectric', 'Sharcastric',
			'Roenin', 'Salmurai', 'Harminth', 'Murkrow', 'Honchkrow', 'Croagunk', 'Toxicroak', 'Dreepy', 'Drakloak', 'Dragapult', 'Sweeptite', 'Dustrega', 'Librareek', 'Calligrave',
			'Authorror', 'Ghostage', 'Paranormail', 'Deliveerie', 'Romirror', 'Resufflect', 'Mimikyu', 'Mudbray', 'Mudsdale', 'Meduzap', 'Gorgowatt', 'Skarmory', 'Delibird', 'Brawnze',
			'Silvictor', 'Goalden', 'Cleffa', 'Clefairy', 'Clefable', 'Protauri', 'Stargazaur', 'Kaijupiter', 'Minior', 'Shuckle', 'Recorvid', 'Survulture', 'Culprint', 'Underhandit', 'Eggad',
			'Ornamelt', 'Klink', 'Klang', 'Klinklang', 'Djironn', 'Forgenie', 'Tinkatink', 'Tinkatuff', 'Tinkaton', 'Riskard', 'Riskard-Diamonds', 'Riskard-Clubs', 'Riskard-Spades', 'Dektout',
			'Dektout-Diamonds', 'Dektout-Clubs', 'Dektout-Spades', 'Beldum', 'Metang', 'Metagross', 'Cetoddle', 'Cetitan', 'Druddigon-Novrai', 'Munchlax', 'Snorlax', 'Puriphin', 'Dumpback',
			'Allywag', 'Avigate', 'Scurvessel', 'Dondozo', 'Tatsugiri', 'Elekid', 'Electabuzz', 'Electivire', 'Magby', 'Magmar', 'Magmortar', 'Dodojo', 'Taekwondodo', 'Tropius', 'Gligar',
			'Gliscor', 'Skorupi', 'Drapion', 'Karroot', 'Kerratic', 'Rufflet', 'Braviary', 'Vullaby', 'Mandibuzz', 'Gluctose', 'Onychew', 'Gummiwyrm', 'Foolmingo', 'Pitcharade', 'Bonfird',
			'Conflagrace', 'Kappow', 'Kappatoa', 'Trapinch', 'Vibrava', 'Flygon', 'Slithm', 'Spiroll', 'Percusshell', 'Gnomad', 'Gnoblety', 'Gnotorious', 'Ohman', 'Ohmigosh', 'Papernova',
			'Orbitgami', 'Scyther', 'Scizor', 'Kleavor', 'Elepath', 'Wackyderm', 'Jangmo-o', 'Hakamo-o', 'Kommo-o', 'Varanox', 'Halitox', 'Juroxic', 'Snowitall', 'Subzerebrum', 'Amygdalanche',
			'Stantler', 'Wyrdeer', 'Swinub', 'Piloswine', 'Mamoswine', 'Pinguin', 'Pingushion', 'Arctire', 'Iccelerate', 'Psyclops', 'Psyphemus', 'Bagon', 'Shelgon', 'Salamence', 'Ballistyke',
			'Celestorch', 'Spheal', 'Sealeo', 'Walrein', 'Lapras-Novrai', 'Whirlpoon', 'Sirenaut', 'Dhelmise', 'Bristletoe', 'Jollychaete', 'Clamperl', 'Huntail-Novrai', 'Gorebyss-Novrai',
			'Bergmite', 'Avalugg', 'Sneasel', 'Weavile', 'Germelt', 'Contagice', 'Brumalaise', 'Duraludon', 'Kerohelion', 'Larvitar', 'Pupitar', 'Tyranitar', 'Deino', 'Zweilous', 'Hydreigon',
			'Larvesta', 'Volcarona', 'Cadavillar', 'Entomortis', 'X-Lixir', 'Relmirror', 'Gronegardian', 'Magemeltre', 'Krailstorm', 'Surusen', 'Ikarma', 'Nedareap', 'Utsoul', 'Anaither',
			'Mizevaris', 'Chondrius', 'Astroyatlas', 'Migreat', 'Migreat-Okeno'
			],	
			onSwitchIn(pokemon) {
        		this.add('-start', pokemon, 'typechange', pokemon.species.types.join('/'), '[silent]');
        	},	
	},
];